version: '2'
services:
  gh-tg-bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gh-tg-bot
    environment:
      - CLIENT_ID = "gh client id xxxx"
      - SECRET_ID = "gh client secret xxxx"
      - REPOSITORY = "github repository name"
      - OWNER = "owner/organization name"
      - BOT_TOKEN = "telegram bot token"
    networks:
      - gh-bot-network
    ports:
      - '8080:80'
networks:
  gh-bot-network:
    driver: bridge