version: '2'
services:
  gh-tg-bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gh-tg-bot
    env_file:
      - .env
    networks:
      - gh-bot-network
    ports:
      - '8080:80'
networks:
  gh-bot-network:
    driver: bridge